# Generated by Django 5.1.4 on 2024-12-10 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age_user_blood_group_user_gender_user_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('specialization', models.CharField(max_length=100)),
                ('pmdc_number', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('clinic_address', models.TextField()),
                ('medical_certificate', models.FileField(upload_to='doctor_certificates/')),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
