# Generated by Django 5.1.4 on 2024-12-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='role',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
