# Generated by Django 5.1.4 on 2024-12-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_pictures/'),
        ),
    ]
